### ISSUE TITLE
Slowdown in `Intersection` module's Well-pick layer

### ISSUE THREAD

**Issue by Anders2303** [equinor/webviz#724] opened 2024-09-13 07:57 UTC
Adding a well-pick layer to the `Intersection` module causes significant frame-drops

* If the module's settings are open, the settings component's Tree RC count keeps increasing, so there's a re-render loop being triggered somewhere
* Additionally, just having the well-pick layer enabled, cause the entire app to behave slower (without Intersection's settings being open). The view's debug info is stable, so the slowdown is happening somewhere else, but you can clearly see things slowing down when moving the graph around

**Comment by Anders2303** [comment] 2024-09-13 08:05
For the settings, could it be this line from `wellpicksLayer.tsc`?
```typescript
    const [newSettings, setNewSettings] = React.useState<Partial<WellpicksLayerSettings>>({});
    // ...
    React.useEffect(
        function propagateSettingsChange() {
            props.layer.maybeUpdateSettings(newSettings);
            props.layer.maybeRefetchData();
            setNewSettings({});
        },
        [newSettings, props.layer]
    );
```

Wouldnt this effect cause itself to always re-trigger, since it both depends on `newSettings`, and sets it to a new object every time?

**Comment by rubenthoms** [comment] 2024-09-13 15:09
Duplicate of #721 but with more info.

**Comment by rubenthoms** [comment] 2024-09-16 07:22
> For the settings, could it be this line from `wellpicksLayer.tsc`?
> 
> ```ts
>     const [newSettings, setNewSettings] = React.useState<Partial<WellpicksLayerSettings>>({});
>     // ...
>     React.useEffect(
>         function propagateSettingsChange() {
>             props.layer.maybeUpdateSettings(newSettings);
>             props.layer.maybeRefetchData();
>             setNewSettings({});
>         },
>         [newSettings, props.layer]
>     );
> ```
> 
> Wouldnt this effect cause itself to always re-trigger, since it both depends on `newSettings`, and sets it to a new object every time?

Looks like a plausible candidate :+1:

**Closed** 2024-09-18 14:47 UTC
Labels: bug
