### ISSUE TITLE
Integration tests setup

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz#485] opened 2023-11-27 12:15 UTC
What is required?
- Setup test user (Azure Service Principal) with application access to `Sumo.Read` (requires permission from Equinor responsible)
- Authenticate with token in `env` towards backend
- Create cases with test data in `Sumo - Drogon`
    - How to keep test data unmodified (does not lead to failing other tests)
    - How to revision test data (updating + adding new)

**Comment by anders-kiaer** [comment] 2024-10-29 08:21
Duplicate of #548

**Closed by anders-kiaer** 2024-10-29 08:21 UTC
Labels: enhancement, epic
